[project]
name        = "std"
version     = "0.0.1"
authors     = ["dalance@gmail.com"]
description = "Veryl Standard Library"
license     = "MIT OR Apache-2.0"
repository  = "https://github.com/veryl-lang/std"

[build]
target = {type = "directory", path = "target/src"}

[doc]
path = "target/doc"
