name: Deploy

on:
  push:
    branches:
      - main

jobs:
  book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Build veryl
        run: cargo install --git https://github.com/veryl-lang/veryl veryl
      - name: Build doc
        run: veryl doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc
          cname: std.veryl-lang.org
