name: Regression

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Setup veryl
        run:  cargo install --git https://github.com/veryl-lang/veryl veryl
      - name: Format check
        run: veryl fmt --check
      - name: Build check
        run: veryl check
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Setup veryl
        run:  cargo install --git https://github.com/veryl-lang/veryl veryl
      - name: Setup verilator
        uses: veryl-lang/setup-verilator@v1
      - name: Test
        run: veryl test --sim verilator
