name: Regression

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup veryl
        uses: veryl-lang/setup-veryl@v1
      - name: Format check
        run: veryl fmt --check
      - name: Build check
        run: veryl check
