name: Regression

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup veryl
        uses: veryl-lang/setup-veryl@v1
      - name: Format check
        run: veryl fmt --check
      - name: Build check
        run: veryl check
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup veryl
        uses: veryl-lang/setup-veryl@v1
      - name: Setup verilator
        uses: veryl-lang/setup-verilator@v1
      - run: sudo apt-get install -y ccache
      - name: Test
        run: veryl test --sim verilator --verbose
